SET hive.stats.autogather=false;
SET hive.exec.compress.output=true; 
SET mapred.output.compression.codec=org.apache.hadoop.io.compress.SnappyCodec; 
SET mapred.output.compression.type=BLOCK;
SET hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;

USE gfora;

DROP TABLE MODEL_DETAIL_BUSINESSPHONE_DRV;

CREATE TABLE MODEL_DETAIL_BUSINESSPHONE_DRV
ROW FORMAT DELIMITED
STORED AS SEQUENCEFILE
AS

SELECT
 d.FRAUD_TRANSACTION_ID
,max(case 
      when d.row_num = 1 then d.TRAVELER_BUSINESS_PHONE_DERIVED_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_DERIVED_1
,max(case 
      when d.row_num = 1 then d.TRAVELER_BUSINESS_PHONE_AREA_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_AREA_CODE_1
,max(case 
      when d.row_num = 1 then d.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_1
,max(case 
      when d.row_num = 1 then d.TRAVELER_BUSINESS_PHONE_NUMBER_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_NUMBER_1	 
,max(case 
      when d.row_num = 2 then d.TRAVELER_BUSINESS_PHONE_DERIVED_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_DERIVED_2
,max(case 
      when d.row_num = 2 then d.TRAVELER_BUSINESS_PHONE_AREA_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_AREA_CODE_2
,max(case 
      when d.row_num = 2 then d.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_2
,max(case 
      when d.row_num = 2 then d.TRAVELER_BUSINESS_PHONE_NUMBER_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_NUMBER_2
,max(case 
      when d.row_num = 3 then d.TRAVELER_BUSINESS_PHONE_DERIVED_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_DERIVED_3
,max(case 
      when d.row_num = 3 then d.TRAVELER_BUSINESS_PHONE_AREA_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_AREA_CODE_3
,max(case 
      when d.row_num = 3 then d.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_3
,max(case 
      when d.row_num = 3 then d.TRAVELER_BUSINESS_PHONE_NUMBER_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_NUMBER_3
,max(case 
      when d.row_num = 4 then d.TRAVELER_BUSINESS_PHONE_DERIVED_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_DERIVED_4
,max(case 
      when d.row_num = 4 then d.TRAVELER_BUSINESS_PHONE_AREA_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_AREA_CODE_4
,max(case 
      when d.row_num = 4 then d.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_4
,max(case 
      when d.row_num = 4 then d.TRAVELER_BUSINESS_PHONE_NUMBER_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_NUMBER_4
,max(case 
      when d.row_num = 5 then d.TRAVELER_BUSINESS_PHONE_DERIVED_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_DERIVED_5
,max(case 
      when d.row_num = 5 then d.TRAVELER_BUSINESS_PHONE_AREA_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_AREA_CODE_5
,max(case 
      when d.row_num = 5 then d.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_5
,max(case 
      when d.row_num = 5 then d.TRAVELER_BUSINESS_PHONE_NUMBER_n 
      else ''
     end) AS TRAVELER_BUSINESS_PHONE_NUMBER_5
FROM
(
 SELECT
  c.FRAUD_TRANSACTION_ID
 ,c.TRAVELER_BUSINESS_PHONE_DERIVED_n
 ,c.TRAVELER_BUSINESS_PHONE_AREA_CODE_n
 ,c.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
 ,c.TRAVELER_BUSINESS_PHONE_NUMBER_n
 ,row_number(c.FRAUD_TRANSACTION_ID) as row_num
 FROM
 (
  SELECT
   b.FRAUD_TRANSACTION_ID
  ,b.TRAVELER_BUSINESS_PHONE_DERIVED_n
  ,b.TRAVELER_BUSINESS_PHONE_AREA_CODE_n
  ,b.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
  ,b.TRAVELER_BUSINESS_PHONE_NUMBER_n
  FROM
  (
   SELECT
     a.FRAUD_TRANSACTION_ID
    ,a.TRAVELER_BUSINESS_PHONE_DERIVED_n
    ,a.TRAVELER_BUSINESS_PHONE_AREA_CODE_n
    ,a.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
    ,a.TRAVELER_BUSINESS_PHONE_NUMBER_n
   FROM
   (
    SELECT
      FRAUD_TRANSACTION_ID
     ,TRAVELER_1_BUSINESS_PHONE_DERIVED as TRAVELER_BUSINESS_PHONE_DERIVED_n
     ,TRAVELER_1_BUSINESS_PHONE_AREA_CODE as TRAVELER_BUSINESS_PHONE_AREA_CODE_n
     ,TRAVELER_1_BUSINESS_PHONE_COUNTRY_ACCESS_CODE as TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
     ,TRAVELER_1_BUSINESS_PHONE_NUMBER as TRAVELER_BUSINESS_PHONE_NUMBER_n
    FROM
    gfora.FRAUD_SCORING_XML_MODEL_DETAIL_DRV1
    WHERE TRAVELER_1_BUSINESS_PHONE_DERIVED <> ''

    UNION ALL
    SELECT
      FRAUD_TRANSACTION_ID
     ,TRAVELER_2_BUSINESS_PHONE_DERIVED as TRAVELER_BUSINESS_PHONE_DERIVED_n
     ,TRAVELER_2_BUSINESS_PHONE_AREA_CODE as TRAVELER_BUSINESS_PHONE_AREA_CODE_n
     ,TRAVELER_2_BUSINESS_PHONE_COUNTRY_ACCESS_CODE as TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
     ,TRAVELER_2_BUSINESS_PHONE_NUMBER as TRAVELER_BUSINESS_PHONE_NUMBER_n
    FROM
    gfora.FRAUD_SCORING_XML_MODEL_DETAIL_DRV1
    WHERE TRAVELER_2_BUSINESS_PHONE_DERIVED <> ''

    UNION ALL
    SELECT
      FRAUD_TRANSACTION_ID
     ,TRAVELER_3_BUSINESS_PHONE_DERIVED as TRAVELER_BUSINESS_PHONE_DERIVED_n
     ,TRAVELER_3_BUSINESS_PHONE_AREA_CODE as TRAVELER_BUSINESS_PHONE_AREA_CODE_n
     ,TRAVELER_3_BUSINESS_PHONE_COUNTRY_ACCESS_CODE as TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
     ,TRAVELER_3_BUSINESS_PHONE_NUMBER as TRAVELER_BUSINESS_PHONE_NUMBER_n
    FROM
    gfora.FRAUD_SCORING_XML_MODEL_DETAIL_DRV1
    WHERE TRAVELER_3_BUSINESS_PHONE_DERIVED <> ''

    UNION ALL
    SELECT
      FRAUD_TRANSACTION_ID
     ,TRAVELER_4_BUSINESS_PHONE_DERIVED as TRAVELER_BUSINESS_PHONE_DERIVED_n
     ,TRAVELER_4_BUSINESS_PHONE_AREA_CODE as TRAVELER_BUSINESS_PHONE_AREA_CODE_n
     ,TRAVELER_4_BUSINESS_PHONE_COUNTRY_ACCESS_CODE as TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
     ,TRAVELER_4_BUSINESS_PHONE_NUMBER as TRAVELER_BUSINESS_PHONE_NUMBER_n
    FROM
    gfora.FRAUD_SCORING_XML_MODEL_DETAIL_DRV1
    WHERE TRAVELER_4_BUSINESS_PHONE_DERIVED <> ''

    UNION ALL
    SELECT
      FRAUD_TRANSACTION_ID
     ,TRAVELER_5_BUSINESS_PHONE_DERIVED as TRAVELER_BUSINESS_PHONE_DERIVED_n
     ,TRAVELER_5_BUSINESS_PHONE_AREA_CODE as TRAVELER_BUSINESS_PHONE_AREA_CODE_n
     ,TRAVELER_5_BUSINESS_PHONE_COUNTRY_ACCESS_CODE as TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
     ,TRAVELER_5_BUSINESS_PHONE_NUMBER as TRAVELER_BUSINESS_PHONE_NUMBER_n
    FROM
    gfora.FRAUD_SCORING_XML_MODEL_DETAIL_DRV1
    WHERE TRAVELER_5_BUSINESS_PHONE_DERIVED <> ''
    ) a
   GROUP BY
    a.FRAUD_TRANSACTION_ID
   ,a.TRAVELER_BUSINESS_PHONE_DERIVED_n
   ,a.TRAVELER_BUSINESS_PHONE_AREA_CODE_n
   ,a.TRAVELER_BUSINESS_PHONE_COUNTRY_ACCESS_CODE_n
   ,a.TRAVELER_BUSINESS_PHONE_NUMBER_n
   ) b
  DISTRIBUTE BY b.FRAUD_TRANSACTION_ID
  SORT BY b.FRAUD_TRANSACTION_ID, b.TRAVELER_BUSINESS_PHONE_DERIVED_n desc
 ) c
) d
GROUP BY
d.FRAUD_TRANSACTION_ID
;

