USE gfora;

DROP TABLE fraud_weighted_scorecard_flat_source_v7_velocity_uday;

CREATE TABLE fraud_weighted_scorecard_flat_source_v7_velocity_uday
ROW FORMAT DELIMITED
STORED AS SEQUENCEFILE
AS

SELECT a.*
,b.account_home_phone_country_access_code_30days_count
,b.account_home_phone_country_access_code_item_amount_usd_derived_30days_sum
,b.ip_continent_30days_count
,b.ip_continent_item_amount_usd_derived_30days_sum
,b.accountnum_30days_count
,b.accountnum_item_amount_usd_derived_30days_sum
,b.ip_address_cidr_30days_count
,b.ip_address_cidr_item_amount_usd_derived_30days_sum
,b.ip_top_level_domain_30days_count
,b.ip_top_level_domain_item_amount_usd_derived_30days_sum
,b.account_company_name_30days_count
,b.account_company_name_item_amount_usd_derived_30days_sum
,b.account_person_name_30days_count
,b.account_person_name_item_amount_usd_derived_30days_sum
,b.frequentflyernumber_1_30days_count
,b.frequentflyernumber_1_item_amount_usd_derived_30days_sum
,b.frequentflyernumber_1_machine_id_30days_bi_count-1 as frequentflyernumber_1_machine_id_30days_bi_count 
,b.frequentflyernumber_1_ip_address_30days_bi_count-1 as frequentflyernumber_1_ip_address_30days_bi_count
,b.frequentflyernumber_1_account_email_30days_bi_count-1 as frequentflyernumber_1_account_email_30days_bi_count
,b.frequentflyernumber_1_account_id_30days_bi_count-1 as frequentflyernumber_1_account_id_30days_bi_count
,b.frequentflyernumber_1_account_password_30days_bi_count-1 as frequentflyernumber_1_account_password_30days_bi_count
,b.frequentflyernumber_1_traveler_email_address_1_30days_bi_count-1 as frequentflyernumber_1_traveler_email_address_1_30days_bi_count 
,b.frequentflyernumber_1_payment_email_address_1_30days_bi_count-1 as frequentflyernumber_1_payment_email_address_1_30days_bi_count
,b.frequentflyernumber_1_payment_phone_number_1_30days_bi_count-1 as frequentflyernumber_1_payment_phone_number_1_30days_bi_count
,b.frequentflyernumber_1_tsatravelid_1_30days_bi_count-1 as frequentflyernumber_1_tsatravelid_1_30days_bi_count
,b.frequentflyernumber_1_passportnumber_1_30days_bi_count-1 as frequentflyernumber_1_passportnumber_1_30days_bi_count
,b.frequentflyernumber_1_payment_hashed_credit_card_number_1_30days_bi_count-1 as frequentflyernumber_1_payment_hashed_credit_card_number_1_30days_bi_count
,b.frequentflyernumber_1_item_destination_1_30days_bi_count-1 as frequentflyernumber_1_item_destination_1_30days_bi_count
,b.ip_city_30days_count
,b.ip_city_item_amount_usd_derived_30days_sum
,b.tsatravelid_1_30days_count
,b.tsatravelid_1_item_amount_usd_derived_30days_sum
,b.tsatravelid_1_machine_id_30days_bi_count-1 as tsatravelid_1_machine_id_30days_bi_count
,b.tsatravelid_1_ip_address_30days_bi_count-1 as tsatravelid_1_ip_address_30days_bi_count
,b.tsatravelid_1_account_email_30days_bi_count-1 as tsatravelid_1_account_email_30days_bi_count
,b.tsatravelid_1_account_id_30days_bi_count-1 as tsatravelid_1_account_id_30days_bi_count
,b.tsatravelid_1_account_password_30days_bi_count-1 as tsatravelid_1_account_password_30days_bi_count
,b.tsatravelid_1_traveler_email_address_1_30days_bi_count-1 as tsatravelid_1_traveler_email_address_1_30days_bi_count
,b.tsatravelid_1_payment_email_address_1_30days_bi_count-1 as tsatravelid_1_payment_email_address_1_30days_bi_count
,b.tsatravelid_1_payment_phone_number_1_30days_bi_count-1 as tsatravelid_1_payment_phone_number_1_30days_bi_count
,b.tsatravelid_1_frequentflyernumber_1_30days_bi_count-1 as tsatravelid_1_frequentflyernumber_1_30days_bi_count
,b.tsatravelid_1_passportnumber_1_30days_bi_count-1 as tsatravelid_1_passportnumber_1_30days_bi_count
,b.tsatravelid_1_payment_hashed_credit_card_number_1_30days_bi_count-1 as tsatravelid_1_payment_hashed_credit_card_number_1_30days_bi_count
,b.tsatravelid_1_item_destination_1_30days_bi_count-1 as tsatravelid_1_item_destination_1_30days_bi_count
,b.ip_postal_code_30days_count
,b.ip_postal_code_item_amount_usd_derived_30days_sum
,b.item_postal_code_1_30days_count
,b.item_postal_code_1_item_amount_usd_derived_30days_sum
,b.account_password_30days_count
,b.account_password_item_amount_usd_derived_30days_sum
,b.account_password_machine_id_30days_bi_count-1 as account_password_machine_id_30days_bi_count
,b.account_password_ip_address_30days_bi_count-1 as account_password_ip_address_30days_bi_count
,b.account_password_account_email_30days_bi_count-1 as account_password_account_email_30days_bi_count
,b.account_password_account_id_30days_bi_count-1 as account_password_account_id_30days_bi_count
,b.account_password_traveler_email_address_1_30days_bi_count-1 as account_password_traveler_email_address_1_30days_bi_count
,b.account_password_payment_email_address_1_30days_bi_count-1 as account_password_payment_email_address_1_30days_bi_count
,b.account_password_payment_phone_number_1_30days_bi_count-1 as account_password_payment_phone_number_1_30days_bi_count
,b.account_password_tsatravelid_1_30days_bi_count-1 as account_password_tsatravelid_1_30days_bi_count
,b.account_password_frequentflyernumber_1_30days_bi_count-1 as  account_password_frequentflyernumber_1_30days_bi_count
,b.account_password_passportnumber_1_30days_bi_count-1 as account_password_passportnumber_1_30days_bi_count
,b.account_password_payment_hashed_credit_card_number_1_30days_bi_count-1 as account_password_payment_hashed_credit_card_number_1_30days_bi_count
,b.account_password_item_destination_1_30days_bi_count-1 as account_password_item_destination_1_30days_bi_count
,b.payment_last_name_1_30days_count
,b.payment_last_name_1_item_amount_usd_derived_30days_sum
,b.payment_email_address_1_30days_count
,b.payment_email_address_1_item_amount_usd_derived_30days_sum
,b.payment_email_address_1_machine_id_30days_bi_count-1 as payment_email_address_1_machine_id_30days_bi_count
,b.payment_email_address_1_ip_address_30days_bi_count-1 as  payment_email_address_1_ip_address_30days_bi_count
,b.payment_email_address_1_account_email_30days_bi_count-1 as  payment_email_address_1_account_email_30days_bi_count
,b.payment_email_address_1_account_id_30days_bi_count-1 as payment_email_address_1_account_id_30days_bi_count
,b.payment_email_address_1_account_password_30days_bi_count-1 as payment_email_address_1_account_password_30days_bi_count
,b.payment_email_address_1_traveler_email_address_1_30days_bi_count-1 as payment_email_address_1_traveler_email_address_1_30days_bi_count
,b.payment_email_address_1_payment_phone_number_1_30days_bi_count-1 as payment_email_address_1_payment_phone_number_1_30days_bi_count
,b.payment_email_address_1_tsatravelid_1_30days_bi_count-1 as payment_email_address_1_tsatravelid_1_30days_bi_count
,b.payment_email_address_1_frequentflyernumber_1_30days_bi_count-1 as payment_email_address_1_frequentflyernumber_1_30days_bi_count
,b.payment_email_address_1_passportnumber_1_30days_bi_count-1 as payment_email_address_1_passportnumber_1_30days_bi_count
,b.payment_email_address_1_payment_hashed_credit_card_number_1_30days_bi_count-1 as payment_email_address_1_payment_hashed_credit_card_number_1_30days_bi_count
,b.payment_email_address_1_item_destination_1_30days_bi_count-1 as payment_email_address_1_item_destination_1_30days_bi_count
,b.ip_routing_method_30days_count
,b.ip_routing_method_item_amount_usd_derived_30days_sum
,b.traveler_full_name_1_30days_count
,b.traveler_full_name_1_item_amount_usd_derived_30days_sum
,b.item_airport_pick_up_location_1_30days_count
,b.item_airport_pick_up_location_1_item_amount_usd_derived_30days_sum
,b.account_email_30days_count
,b.account_email_item_amount_usd_derived_30days_sum
,b.account_email_machine_id_30days_bi_count-1 as account_email_machine_id_30days_bi_count
,b.account_email_ip_address_30days_bi_count-1 as account_email_ip_address_30days_bi_count
,b.account_email_account_id_30days_bi_count-1 as account_email_account_id_30days_bi_count
,b.account_email_account_password_30days_bi_count-1 as account_email_account_password_30days_bi_count
,b.account_email_traveler_email_address_1_30days_bi_count-1 as account_email_traveler_email_address_1_30days_bi_count
,b.account_email_payment_email_address_1_30days_bi_count-1 as account_email_payment_email_address_1_30days_bi_count
,b.account_email_payment_phone_number_1_30days_bi_count-1 as account_email_payment_phone_number_1_30days_bi_count
,b.account_email_tsatravelid_1_30days_bi_count-1 as account_email_tsatravelid_1_30days_bi_count
,b.account_email_frequentflyernumber_1_30days_bi_count-1 as account_email_frequentflyernumber_1_30days_bi_count
,b.account_email_passportnumber_1_30days_bi_count-1 as account_email_passportnumber_1_30days_bi_count
,b.account_email_payment_hashed_credit_card_number_1_30days_bi_count-1 as account_email_payment_hashed_credit_card_number_1_30days_bi_count
,b.account_email_item_destination_1_30days_bi_count-1 as account_email_item_destination_1_30days_bi_count
,b.payment_issue_country_1_30days_count
,b.payment_issue_country_1_item_amount_usd_derived_30days_sum
,b.passportnumber_1_30days_count
,b.passportnumber_1_item_amount_usd_derived_30days_sum
,b.passportnumber_1_machine_id_30days_bi_count-1 as passportnumber_1_machine_id_30days_bi_count
,b.passportnumber_1_ip_address_30days_bi_count-1 as passportnumber_1_ip_address_30days_bi_count
,b.passportnumber_1_account_email_30days_bi_count-1 as passportnumber_1_account_email_30days_bi_count
,b.passportnumber_1_account_id_30days_bi_count-1 as passportnumber_1_account_id_30days_bi_count
,b.passportnumber_1_account_password_30days_bi_count-1 as passportnumber_1_account_password_30days_bi_count
,b.passportnumber_1_traveler_email_address_1_30days_bi_count-1 as passportnumber_1_traveler_email_address_1_30days_bi_count
,b.passportnumber_1_payment_email_address_1_30days_bi_count-1 as passportnumber_1_payment_email_address_1_30days_bi_count
,b.passportnumber_1_payment_phone_number_1_30days_bi_count-1 as passportnumber_1_payment_phone_number_1_30days_bi_count
,b.passportnumber_1_tsatravelid_1_30days_bi_count-1 as passportnumber_1_tsatravelid_1_30days_bi_count
,b.passportnumber_1_frequentflyernumber_1_30days_bi_count-1 as passportnumber_1_frequentflyernumber_1_30days_bi_count
,b.passportnumber_1_payment_hashed_credit_card_number_1_30days_bi_count-1 as passportnumber_1_payment_hashed_credit_card_number_1_30days_bi_count
,b.passportnumber_1_item_destination_1_30days_bi_count-1 as passportnumber_1_item_destination_1_30days_bi_count
,b.item_city_1_30days_count
,b.item_city_1_item_amount_usd_derived_30days_sum
,b.item_vendor_name_1_30days_count
,b.item_vendor_name_1_item_amount_usd_derived_30days_sum
,b.machine_id_30days_count
,b.machine_id_item_amount_usd_derived_30days_sum
,b.machine_id_ip_address_30days_bi_count-1 as machine_id_ip_address_30days_bi_count
,b.machine_id_account_email_30days_bi_count-1 as machine_id_account_email_30days_bi_count
,b.machine_id_account_id_30days_bi_count-1 as  machine_id_account_id_30days_bi_count
,b.machine_id_account_password_30days_bi_count-1 as  machine_id_account_password_30days_bi_count
,b.machine_id_traveler_email_address_1_30days_bi_count-1 as machine_id_traveler_email_address_1_30days_bi_count
,b.machine_id_payment_email_address_1_30days_bi_count-1 as machine_id_payment_email_address_1_30days_bi_count
,b.machine_id_payment_phone_number_1_30days_bi_count-1 as machine_id_payment_phone_number_1_30days_bi_count
,b.machine_id_tsatravelid_1_30days_bi_count-1 as machine_id_tsatravelid_1_30days_bi_count
,b.machine_id_frequentflyernumber_1_30days_bi_count-1 as machine_id_frequentflyernumber_1_30days_bi_count
,b.machine_id_passportnumber_1_30days_bi_count-1 as machine_id_passportnumber_1_30days_bi_count
,b.machine_id_payment_hashed_credit_card_number_1_30days_bi_count-1 as machine_id_payment_hashed_credit_card_number_1_30days_bi_count
,b.machine_id_item_destination_1_30days_bi_count-1 as machine_id_item_destination_1_30days_bi_count
,b.ip_carrier_30days_count
,b.ip_carrier_item_amount_usd_derived_30days_sum
,b.account_id_30days_count
,b.account_id_item_amount_usd_derived_30days_sum
,b.account_id_machine_id_30days_bi_count-1 as account_id_machine_id_30days_bi_count 
,b.account_id_ip_address_30days_bi_count-1 as account_id_ip_address_30days_bi_count
,b.account_id_account_email_30days_bi_count-1 as account_id_account_email_30days_bi_count
,b.account_id_account_password_30days_bi_count-1 as account_id_account_password_30days_bi_count
,b.account_id_traveler_email_address_1_30days_bi_count-1 as account_id_traveler_email_address_1_30days_bi_count
,b.account_id_payment_email_address_1_30days_bi_count-1 as account_id_payment_email_address_1_30days_bi_count
,b.account_id_payment_phone_number_1_30days_bi_count-1 as account_id_payment_phone_number_1_30days_bi_count
,b.account_id_tsatravelid_1_30days_bi_count-1 as account_id_tsatravelid_1_30days_bi_count
,b.account_id_frequentflyernumber_1_30days_bi_count-1 as account_id_frequentflyernumber_1_30days_bi_count
,b.account_id_passportnumber_1_30days_bi_count-1 as account_id_passportnumber_1_30days_bi_count
,b.account_id_payment_hashed_credit_card_number_1_30days_bi_count-1 as account_id_payment_hashed_credit_card_number_1_30days_bi_count
,b.account_id_item_destination_1_30days_bi_count-1 as account_id_item_destination_1_30days_bi_count
,b.item_destination_1_30days_count
,b.item_destination_1_item_amount_usd_derived_30days_sum
,b.account_home_phone_area_code_30days_count
,b.account_home_phone_area_code_item_amount_usd_derived_30days_sum
,b.item_airport_drop_off_location_1_30days_count
,b.item_airport_drop_off_location_1_item_amount_usd_derived_30days_sum
,b.ip_country_30days_count
,b.ip_country_item_amount_usd_derived_30days_sum
,b.transaction_guid_30days_count
,b.transaction_guid_item_amount_usd_derived_30days_sum
,b.ip_address_asn_30days_count
,b.ip_address_asn_item_amount_usd_derived_30days_sum
,b.ip_time_zone_30days_count
,b.ip_time_zone_item_amount_usd_derived_30days_sum
,b.ip_area_code_30days_count
,b.ip_area_code_item_amount_usd_derived_30days_sum
,b.loyalty_member_id_30days_count
,b.loyalty_member_id_item_amount_usd_derived_30days_sum
,b.payment_hashed_credit_card_number_1_30days_count
,b.payment_hashed_credit_card_number_1_item_amount_usd_derived_30days_sum
,b.payment_hashed_credit_card_number_1_machine_id_30days_bi_count-1 as payment_hashed_credit_card_number_1_machine_id_30days_bi_count
,b.payment_hashed_credit_card_number_1_ip_address_30days_bi_count-1 as payment_hashed_credit_card_number_1_ip_address_30days_bi_count
,b.payment_hashed_credit_card_number_1_account_email_30days_bi_count-1 as payment_hashed_credit_card_number_1_account_email_30days_bi_count
,b.payment_hashed_credit_card_number_1_account_id_30days_bi_count-1 as payment_hashed_credit_card_number_1_account_id_30days_bi_count
,b.payment_hashed_credit_card_number_1_account_password_30days_bi_count-1 as payment_hashed_credit_card_number_1_account_password_30days_bi_count
,b.payment_hashed_credit_card_number_1_traveler_email_address_1_30days_bi_count-1 as payment_hashed_credit_card_number_1_traveler_email_address_1_30days_bi_coun
,b.payment_hashed_credit_card_number_1_payment_email_address_1_30days_bi_count-1 as payment_hashed_credit_card_number_1_payment_email_address_1_30days_bi_count
,b.payment_hashed_credit_card_number_1_payment_phone_number_1_30days_bi_count-1 as payment_hashed_credit_card_number_1_payment_phone_number_1_30days_bi_count
,b.payment_hashed_credit_card_number_1_tsatravelid_1_30days_bi_count-1 as payment_hashed_credit_card_number_1_tsatravelid_1_30days_bi_count
,b.payment_hashed_credit_card_number_1_frequentflyernumber_1_30days_bi_count-1 as payment_hashed_credit_card_number_1_frequentflyernumber_1_30days_bi_count
,b.payment_hashed_credit_card_number_1_passportnumber_1_30days_bi_count-1 as payment_hashed_credit_card_number_1_passportnumber_1_30days_bi_count
,b.payment_hashed_credit_card_number_1_item_destination_1_30days_bi_count-1 as payment_hashed_credit_card_number_1_item_destination_1_30days_bi_count
,b.payment_phone_number_1_30days_count
,b.payment_phone_number_1_item_amount_usd_derived_30days_sum
,b.payment_phone_number_1_machine_id_30days_bi_count-1 as payment_phone_number_1_machine_id_30days_bi_count
,b.payment_phone_number_1_ip_address_30days_bi_count-1 as payment_phone_number_1_ip_address_30days_bi_count
,b.payment_phone_number_1_account_email_30days_bi_count-1 as payment_phone_number_1_account_email_30days_bi_count
,b.payment_phone_number_1_account_id_30days_bi_count-1 as payment_phone_number_1_account_id_30days_bi_count
,b.payment_phone_number_1_account_password_30days_bi_count-1 as payment_phone_number_1_account_password_30days_bi_count
,b.payment_phone_number_1_traveler_email_address_1_30days_bi_count-1 as payment_phone_number_1_traveler_email_address_1_30days_bi_count
,b.payment_phone_number_1_payment_email_address_1_30days_bi_count-1 as payment_phone_number_1_payment_email_address_1_30days_bi_count
,b.payment_phone_number_1_tsatravelid_1_30days_bi_count-1 as payment_phone_number_1_tsatravelid_1_30days_bi_count
,b.payment_phone_number_1_frequentflyernumber_1_30days_bi_count-1 as payment_phone_number_1_frequentflyernumber_1_30days_bi_count
,b.payment_phone_number_1_passportnumber_1_30days_bi_count-1 as payment_phone_number_1_passportnumber_1_30days_bi_count
,b.payment_phone_number_1_payment_hashed_credit_card_number_1_30days_bi_count-1 as payment_phone_number_1_payment_hashed_credit_card_number_1_30days_bi_count
,b.payment_phone_number_1_item_destination_1_30days_bi_count-1 as payment_phone_number_1_item_destination_1_30days_bi_count
,b.traveler_email_address_1_30days_count
,b.traveler_email_address_1_item_amount_usd_derived_30days_sum
,b.traveler_email_address_1_machine_id_30days_bi_count-1 as traveler_email_address_1_machine_id_30days_bi_count
,b.traveler_email_address_1_ip_address_30days_bi_count-1 as traveler_email_address_1_ip_address_30days_bi_count
,b.traveler_email_address_1_account_email_30days_bi_count-1 as traveler_email_address_1_account_email_30days_bi_count
,b.traveler_email_address_1_account_id_30days_bi_count-1 as traveler_email_address_1_account_id_30days_bi_count
,b.traveler_email_address_1_account_password_30days_bi_count-1 as traveler_email_address_1_account_password_30days_bi_count
,b.traveler_email_address_1_payment_email_address_1_30days_bi_count-1 as traveler_email_address_1_payment_email_address_1_30days_bi_count
,b.traveler_email_address_1_payment_phone_number_1_30days_bi_count-1 as traveler_email_address_1_payment_phone_number_1_30days_bi_count
,b.traveler_email_address_1_tsatravelid_1_30days_bi_count-1 as traveler_email_address_1_tsatravelid_1_30days_bi_count
,b.traveler_email_address_1_frequentflyernumber_1_30days_bi_count-1 as traveler_email_address_1_frequentflyernumber_1_30days_bi_count
,b.traveler_email_address_1_passportnumber_1_30days_bi_count-1 as traveler_email_address_1_passportnumber_1_30days_bi_count
,b.traveler_email_address_1_payment_hashed_credit_card_number_1_30days_bi_count-1 as traveler_email_address_1_payment_hashed_credit_card_number_1_30days_bi_count
,b.traveler_email_address_1_item_destination_1_30days_bi_count-1 as traveler_email_address_1_item_destination_1_30days_bi_count
,b.ip_address_30days_count
,b.ip_address_item_amount_usd_derived_30days_sum
,b.ip_address_machine_id_30days_bi_count-1 as ip_address_machine_id_30days_bi_count
,b.ip_address_account_email_30days_bi_count-1 as ip_address_account_email_30days_bi_count
,b.ip_address_account_id_30days_bi_count-1 as ip_address_account_id_30days_bi_count
,b.ip_address_account_password_30days_bi_count-1 as ip_address_account_password_30days_bi_count
,b.ip_address_traveler_email_address_1_30days_bi_count-1 as ip_address_traveler_email_address_1_30days_bi_count
,b.ip_address_payment_email_address_1_30days_bi_count-1 as ip_address_payment_email_address_1_30days_bi_count
,b.ip_address_payment_phone_number_1_30days_bi_count-1 as ip_address_payment_phone_number_1_30days_bi_count
,b.ip_address_tsatravelid_1_30days_bi_count-1 as ip_address_tsatravelid_1_30days_bi_count
,b.ip_address_frequentflyernumber_1_30days_bi_count-1 as ip_address_frequentflyernumber_1_30days_bi_count
,b.ip_address_passportnumber_1_30days_bi_count-1 as ip_address_passportnumber_1_30days_bi_count
,b.ip_address_payment_hashed_credit_card_number_1_30days_bi_count-1 as ip_address_payment_hashed_credit_card_number_1_30days_bi_count
,b.ip_address_item_destination_1_30days_bi_count-1 as ip_address_item_destination_1_30days_bi_count
,b.vendorcode_1_30days_count
,b.vendorcode_1_item_amount_usd_derived_30days_sum
,b.ip_second_level_domain_30days_count
,b.ip_second_level_domain_item_amount_usd_derived_30days_sum
,b.payment_bin_number_1_30days_count
,b.payment_bin_number_1_item_amount_usd_derived_30days_sum
,b.account_home_phone_number_30days_count
,b.account_home_phone_number_item_amount_usd_derived_30days_sum
,b.item_airports_1_30days_count
,b.item_airports_1_item_amount_usd_derived_30days_sum
,b.accountphonenum_30days_count
,b.accountphonenum_item_amount_usd_derived_30days_sum
,b.ip_reg_org_30days_count
,b.ip_reg_org_item_amount_usd_derived_30days_sum
,b.ip_state_30days_count
,b.ip_state_item_amount_usd_derived_30days_sum
,b.item_hotel_id_1_30days_count
,b.item_hotel_id_1_item_amount_usd_derived_30days_sum
FROM
gfora.fraud_weighted_scorecard_flat_source_v7_rajfinaltable_uday a
LEFT OUTER JOIN
platdev.tmp_velocity_v6 b
ON
a.fraud_transaction_id = b.fraud_transaction_id 
;
